name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend/bookstore-management-system
        file: ./Backend/bookstore-management-system/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bms-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./Frontend/bms
        file: ./Frontend/bms/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bms-frontend:latest

    - name: Build and push database image
      uses: docker/build-push-action@v2
      with:
        context: ./db
        file: ./db/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bms-database:latest